[package]
name = "good_or_bad_day"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
telegram-bot = "0.8"
tokio = { version = "1.8", features = ["full"] }
futures = "0.3"